#!/usr/bin/env python3
"""Append the Blockchain Fundamentals + Bitcoin Internals courses to data/site.js."""
import re

BC = '''  {
    key: "bc", name: "Blockchain Fundamentals", short: "Blockchain", enabled: true, color: "var(--purple)", hex: "#a78bfa",
    tagline: "14 CHAPTERS",
    desc: "The machinery every chain is built from, derived rather than described. Hash functions and commitment, Merkle trees, digital signatures, the double-spend problem, Byzantine fault tolerance and the FLP impossibility, proof-of-work vs proof-of-stake vs classical BFT, fork choice, P2P gossip, and honest comparison across Bitcoin, Ethereum and permissioned chains.",
    chapters: [
      { id:"bc-01", title:"The Problem: Digital Money Without a Bank", desc:"Why a digital coin is trivially copyable, what a bank actually provides (ordering, finality, identity), and the precise definition of the double-spend problem. Chaum's DigiCash, b-money, bit gold, hashcash \\u2014 what each solved and what each left open.", tags:["double-spend","DigiCash","b-money","hashcash"], sim:"Double-spend playground \\u2014 send the same coin twice to two merchants, watch a ledgerless system fail" },
      { id:"bc-02", title:"Hash Functions: Commitment and Puzzle-Friendliness", desc:"Preimage, second-preimage and collision resistance defined precisely; the Merkle\\u2013Damg\\u00e5rd construction and length-extension; SHA-256's compression function round by round; why hashing is the only primitive that is both a commitment and a puzzle.", tags:["SHA-256","Merkle-Damg\\u00e5rd","collision","length extension"], sim:"SHA-256 stepper \\u2014 watch the message schedule and 64 rounds transform a block, bit by bit" },
      { id:"bc-03", title:"Merkle Trees & Authenticated Data Structures", desc:"Committing to N items in one hash; inclusion proofs in O(log n); why SPV clients work; Merkle-Patricia tries and how Ethereum commits to mutable state; sorted-tree non-inclusion proofs; the CVE-2012-2459 duplicate-hash vulnerability.", tags:["Merkle proof","SPV","Patricia trie","CVE-2012-2459"], sim:"Build a Merkle tree, request an inclusion proof, tamper with a leaf and watch verification fail" },
      { id:"bc-04", title:"Digital Signatures & Elliptic Curves", desc:"Public-key signatures as unforgeable authorization; the discrete log problem; secp256k1's curve equation, point addition and scalar multiplication; ECDSA signing and verification derived step by step; nonce reuse as catastrophic key disclosure; Schnorr's linearity and why it enables aggregation.", tags:["secp256k1","ECDSA","Schnorr","nonce reuse"], sim:"Curve explorer \\u2014 add points geometrically, derive a public key, sign, verify, then reuse a nonce and recover the private key" },
      { id:"bc-05", title:"The Ledger: Hash Chains & Tamper Evidence", desc:"Linking blocks by hash so history becomes append-only in evidence if not in fact; what immutability really means (rewriting costs work, not impossibility); timestamping services as the direct ancestor; state vs transaction models.", tags:["hash chain","tamper evidence","timestamping"], sim:"Chain tamperer \\u2014 alter a historical block and watch every subsequent hash break in cascade" },
      { id:"bc-06", title:"Distributed Consensus: FLP, CAP & Byzantine Faults", desc:"Crash faults vs Byzantine faults; the Byzantine Generals problem and the 3f+1 bound; FLP impossibility and how real systems escape it (randomness, synchrony assumptions); CAP and PACELC applied to ledgers; why open-membership consensus is a different problem entirely.", tags:["FLP","Byzantine Generals","3f+1","CAP"], sim:"Byzantine lab \\u2014 run a small network with traitor nodes, watch agreement hold at 3f+1 and shatter below it" },
      { id:"bc-07", title:"Sybil Resistance: Why Voting Doesn't Work", desc:"Open membership means identities are free, so one-node-one-vote is meaningless. The insight that scarce external cost \\u2014 computation, stake, storage \\u2014 replaces identity. Proof-of-work as a Sybil-resistance mechanism first and a consensus mechanism second.", tags:["Sybil attack","scarce resource","open membership"], sim:"Sybil simulator \\u2014 cheaply spawn thousands of identities against a voting scheme, then against proof-of-work" },
      { id:"bc-08", title:"Proof of Work: Difficulty, Nakamoto Consensus & Finality", desc:"The mining puzzle and target arithmetic; why difficulty must retarget; Nakamoto consensus as probabilistic rather than absolute finality; the exponential-decay math of confirmation depth; selfish mining and the 51% threshold; energy as the security budget.", tags:["difficulty target","Nakamoto consensus","probabilistic finality","51%"], sim:"Mining race \\u2014 pit an attacker's hashrate against the network and watch reorg probability fall with each confirmation" },
      { id:"bc-09", title:"Proof of Stake & Classical BFT", desc:"Stake as the scarce resource; nothing-at-stake and long-range attacks and their fixes (slashing, weak subjectivity, checkpoints); Ethereum's Casper FFG plus LMD-GHOST; Tendermint's instant-finality BFT; committee sampling; the honest tradeoff \\u2014 PoS buys efficiency and pays in complexity and subjectivity.", tags:["nothing-at-stake","slashing","Casper FFG","Tendermint"], sim:"Consensus comparator \\u2014 same network and faults, three mechanisms: compare finality time, energy, and failure modes" },
      { id:"bc-10", title:"Forks: Accidental, Soft, Hard & Chain Splits", desc:"Natural forks from propagation delay; the fork-choice rule as the actual consensus algorithm; orphans and uncles; soft forks as rule-tightening (backward compatible) vs hard forks as rule-loosening; activation mechanisms (BIP9, UASF); real splits \\u2014 the 2013 BDB fork, Ethereum/Classic, Bitcoin Cash.", tags:["fork choice","soft vs hard","BIP9","chain split"], sim:"Fork simulator \\u2014 partition the network, watch competing chains grow, then heal and watch the shorter chain's blocks orphan" },
      { id:"bc-11", title:"The P2P Network: Gossip, Propagation & Eclipse Attacks", desc:"Unstructured gossip overlays and why not DHTs; peer discovery and the ~8-outbound topology; inv/getdata flooding vs compact block relay; propagation delay as the direct cause of orphan rate; eclipse attacks, addr poisoning, and the defenses that followed Heilman's 2015 paper.", tags:["gossip","compact blocks","eclipse attack","propagation delay"], sim:"Network propagation \\u2014 watch a block flood a topology, tune latency and connectivity, then eclipse a node" },
      { id:"bc-12", title:"Scaling: The Trilemma, Sharding & Layer 2", desc:"Why a blockchain is a global broadcast medium and therefore bounded; the decentralization/security/scalability trilemma stated precisely; block size and validation cost; state growth as the real long-run constraint; payment channels, rollups (optimistic vs ZK), data availability sampling.", tags:["trilemma","state growth","rollups","data availability"], sim:"Scaling dials \\u2014 raise block size and rate, watch node hardware requirements and centralization pressure climb together" },
      { id:"bc-13", title:"Beyond Currency: Smart Contracts, State & Tokens", desc:"The UTXO model vs the account model and what each makes easy or hard; determinism as a hard requirement; gas as a halting-problem workaround; the EVM's stack machine; reentrancy and The DAO; oracles as the trust boundary contracts cannot escape.", tags:["UTXO vs account","EVM","gas","reentrancy","oracles"], sim:"State model comparator \\u2014 run identical transfers through UTXO and account models, compare parallelism and proof size" },
      { id:"bc-14", title:"Capstone: Build a Blockchain From Scratch", desc:"Implement a working chain in stages \\u2014 hash-linked blocks, a Merkle tree, ECDSA-signed transactions, a mempool, proof-of-work mining with retargeting, fork choice, and P2P propagation between simulated nodes \\u2014 then attack it and watch it defend itself.", tags:["mini chain","mining","fork choice","P2P"], sim:"Full chain sandbox \\u2014 mine, transact, fork the network, mount a 51% attack, and watch the heaviest chain win" }
    ]
  },
  {
    key: "btc", name: "Bitcoin Internals", short: "Bitcoin", enabled: true, color: "var(--btc)", hex: "#f7931a",
    tagline: "16 CHAPTERS",
    desc: "The protocol as actually implemented, byte by byte. Transaction serialization, Script's stack machine, the UTXO set and its database, block validation rules, mining and difficulty retargeting, the P2P wire protocol, SegWit's witness restructuring, Taproot and Schnorr, Lightning's payment channels, and the incidents that shaped every consensus rule.",
    chapters: [
      { id:"btc-01", title:"Genesis: The Whitepaper, Decoded", desc:"The 2008 whitepaper read as an engineering document \\u2014 what each of its nine sections actually claims. The cypherpunk lineage, the genesis block's embedded headline, the first transaction to Hal Finney, and what Satoshi got provably wrong (the simplified 51% analysis).", tags:["whitepaper","genesis block","cypherpunks","Finney"], sim:"Whitepaper walkthrough \\u2014 each claim mapped to the code that implements it and the chapter that explains it" },
      { id:"btc-02", title:"Keys, Addresses & Wallets", desc:"Private key \\u2192 public key \\u2192 address, with every encoding step: SHA-256 + RIPEMD-160, Base58Check and its checksum, Bech32/Bech32m and BCH error detection. HD wallets: BIP32 derivation, hardened vs non-hardened, BIP39 mnemonics and the seed, BIP44 paths, xpub key-leak hazards.", tags:["Base58Check","Bech32","BIP32","BIP39"], sim:"Key derivation stepper \\u2014 watch entropy become a mnemonic, a seed, a chain of keys, and finally an address" },
      { id:"btc-03", title:"Transactions: The Byte Format", desc:"A raw transaction decoded field by field: version, input count, outpoints, scriptSig, sequence, outputs, value in satoshis, scriptPubKey, locktime. VarInt encoding, little-endian byte order and the txid reversal confusion, coinbase transactions, and the fee as an implicit output.", tags:["raw tx","VarInt","outpoint","txid","locktime"], sim:"Transaction decoder \\u2014 paste or build a raw tx, click any byte, see which field it belongs to and why" },
      { id:"btc-04", title:"Script: The Stack Machine", desc:"Bitcoin's deliberately non-Turing-complete language: the stack model, opcode categories, and execution traced step by step. P2PK \\u2192 P2PKH \\u2192 P2SH \\u2192 P2WPKH \\u2192 P2TR as an evolution. Why loops were excluded, why OP_CAT and others were disabled, and what covenants would enable.", tags:["OP_CHECKSIG","P2PKH","P2SH","disabled opcodes"], sim:"Script debugger \\u2014 step any script opcode by opcode, watch the stack, break the signature and see it fail" },
      { id:"btc-05", title:"Signature Hashing: SIGHASH & the Malleability Bug", desc:"What a signature actually commits to; SIGHASH_ALL/NONE/SINGLE/ANYONECANPAY and their uses; the SIGHASH_SINGLE bug returning hash 1; transaction malleability derived precisely and why it blocked payment channels; BIP143's rewritten algorithm and its quadratic-hashing fix.", tags:["SIGHASH","malleability","BIP143","quadratic hashing"], sim:"Malleate a transaction \\u2014 change its txid without invalidating its signature, then re-run under BIP143" },
      { id:"btc-06", title:"The UTXO Set: Bitcoin's Real Database", desc:"Why unspent-output accounting instead of balances; the UTXO set as the only state a node must keep; the LevelDB chainstate layout and its obfuscation key; UTXO commitments and why Bitcoin lacks them; dust, set growth as a systemic cost, and coin selection algorithms.", tags:["chainstate","LevelDB","coin selection","dust","set growth"], sim:"UTXO explorer \\u2014 spend and create outputs, watch the set mutate, and see coin-selection strategies compared" },
      { id:"btc-07", title:"Blocks: Header, Merkle Root & Serialization", desc:"The 80-byte header decoded: version bits, prev block hash, Merkle root, timestamp, nBits, nonce. Compact target encoding; the coinbase transaction and BIP34 height; the block size and weight limits; why the header is exactly what miners hash.", tags:["80-byte header","nBits","coinbase","block weight"], sim:"Block builder \\u2014 assemble transactions, compute the Merkle root, and grind the nonce against a live target" },
      { id:"btc-08", title:"Validation: Every Rule a Block Must Satisfy", desc:"The full consensus checklist in order: proof of work, timestamp bounds, size and weight, coinbase maturity, input existence and value conservation, script execution, sigop limits, BIP30/34/65/66/68/112/113. Consensus-critical vs policy rules \\u2014 and why that distinction is the most dangerous thing in the codebase.", tags:["consensus rules","coinbase maturity","sigops","policy vs consensus"], sim:"Validation gauntlet \\u2014 craft invalid blocks and watch which specific rule rejects each" },
      { id:"btc-09", title:"Mining: Hardware, Pools & Difficulty", desc:"The nonce grind and its exhaustion (extranonce, version rolling); CPU \\u2192 GPU \\u2192 FPGA \\u2192 ASIC and why SHA-256 was so ASIC-friendly; the 2016-block retarget formula and the off-by-one bug; mining pools, shares, and Stratum; block templates, variance, and pool centralization risk.", tags:["extranonce","ASIC","retarget","Stratum","pool shares"], sim:"Mining simulator \\u2014 dial hashrate and watch difficulty retarget, variance, and pool payout smoothing" },
      { id:"btc-10", title:"The P2P Protocol: Messages on the Wire", desc:"The message envelope (magic, command, length, checksum); version/verack handshake; addr and peer discovery via DNS seeds; inv/getdata/tx/block relay; headers-first sync and the 2013 blocks-first pathology; compact blocks (BIP152); transaction relay privacy and Dandelion.", tags:["version handshake","inv/getdata","headers-first","BIP152"], sim:"Wire inspector \\u2014 decode real P2P messages byte by byte and watch a node sync headers then blocks" },
      { id:"btc-11", title:"The Mempool: Fees, Eviction & Replacement", desc:"Policy vs consensus revisited; fee rate in sat/vB and why size not value determines cost; ancestor/descendant package limits; mempool eviction and the minimum relay fee; RBF (BIP125) and CPFP; fee estimation and the fee-market dynamics of a full block.", tags:["sat/vB","RBF","CPFP","package limits","fee estimation"], sim:"Fee market \\u2014 flood the mempool, watch eviction and the fee floor rise, then bump a stuck tx with RBF and CPFP" },
      { id:"btc-12", title:"SegWit: Restructuring the Transaction", desc:"Malleability fixed by moving witnesses outside the txid; the wtxid and the witness Merkle root in the coinbase; block weight as the new limit and the 4 MB/1 MB reality; how a soft fork achieved this via anyone-can-spend; the activation fight, BIP148 UASF, and SegWit2x's collapse.", tags:["witness","wtxid","block weight","UASF","BIP141"], sim:"SegWit comparator \\u2014 same payment as legacy and SegWit: compare txid stability, size, weight and fee" },
      { id:"btc-13", title:"Taproot: Schnorr, MAST & Key Aggregation", desc:"Schnorr signatures (BIP340) and the linearity ECDSA lacks; MuSig2 key aggregation making multisig indistinguishable from single-sig; MAST hiding unexecuted branches; the taproot tweak committing a script tree to a key; Tapscript changes; the privacy and efficiency wins, and what still leaks.", tags:["BIP340","MuSig2","MAST","taproot tweak","Tapscript"], sim:"Taproot builder \\u2014 construct a script tree, spend via key path and script path, and compare what each reveals" },
      { id:"btc-14", title:"Lightning: Payment Channels & Routing", desc:"Why on-chain payments cannot scale; funding a 2-of-2 channel; commitment transactions and asymmetric revocation; HTLCs enabling multi-hop atomicity; onion routing over the channel graph; watchtowers; force closes; and the real constraints \\u2014 liquidity, routing failures, inbound capacity.", tags:["commitment tx","revocation","HTLC","onion routing","watchtower"], sim:"Channel lab \\u2014 open a channel, route a multi-hop HTLC payment, attempt a revoked-state cheat, watch the penalty fire" },
      { id:"btc-15", title:"Incidents: Every Bug That Changed the Rules", desc:"Root-cause analyses of the events that hardened Bitcoin: the 2010 value-overflow bug (184 billion BTC), the 2013 BDB lock fork, CVE-2018-17144 double-spend/crash, the 2015 July fork from SPV mining, and the block size war as a governance case study.", tags:["value overflow","BDB fork","CVE-2018-17144","SPV mining","block size war"], sim:"Incident replay \\u2014 reproduce each bug against a simulated node and apply the fix that shipped" },
      { id:"btc-16", title:"Capstone: Build a Bitcoin Node", desc:"Implement the protocol in stages: serialize and parse real transactions, execute Script, maintain a UTXO set, validate blocks against the consensus rules, mine with correct difficulty, and speak enough of the P2P protocol to sync from a peer. Verified against real mainnet blocks.", tags:["tx parser","Script VM","UTXO set","block validator"], sim:"Your node \\u2014 parse mainnet blocks, validate them, mine on regtest, and reject every malformed block you can craft" }
    ]
  }
'''

p = "data/site.js"
s = open(p, encoding="utf-8").read()

if '"bc-01"' in s:
    print("courses already present — nothing to do")
else:
    # insert before the final "];" of the COURSES array
    m = re.search(r"(const COURSES = \[.*?)(\n\];)", s, re.S)
    s = s[:m.end(1)] + ",\n" + BC.rstrip() + m.group(2) + s[m.end(2):]

    # BUILT ids
    ids = ['"bc-%02d"' % i for i in range(1, 15)] + ['"btc-%02d"' % i for i in range(1, 17)]
    mb = re.search(r"const BUILT = new Set\(\[(.*?)\]\);", s, re.S)
    cur = mb.group(1).rstrip().rstrip(",")
    s = s[:mb.start(1)] + cur + ",\n  " + ", ".join(ids) + "\n" + s[mb.end(1):]

    # labs
    s = s.replace(
        '''  /* wa:    { file:"wa-lab.html",    title:"…", desc:"…" },  */''',
        '''  bc:    { file: "bc-lab.html",
           title: "Blockchain Hands-On Lab",
           desc: "Build a chain from scratch in stages, mine it, fork it, attack it \\u2014 plus consensus simulators and cryptographic primitive workbenches." },
  btc:   { file: "btc-lab.html",
           title: "Bitcoin Hands-On Lab",
           desc: "A regtest node in Docker: craft and sign raw transactions, run Script, mine blocks on demand, inspect the UTXO set, and open a Lightning channel." }
  /* wa:    { file:"wa-lab.html",    title:"…", desc:"…" },  */''')

    # course pages
    s = s.replace(
        'rmq:"course-rabbitmq.html", wa:"course-whatsapp.html" };',
        'rmq:"course-rabbitmq.html", wa:"course-whatsapp.html",\n'
        '                      bc:"course-blockchain.html", btc:"course-bitcoin.html" };')

    open(p, "w", encoding="utf-8").write(s)
    print("added Blockchain Fundamentals (14) + Bitcoin Internals (16)")
